version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:example@mongodb:27017
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=example
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
      - neo4j
    # Note: For development, you'll want to use the host's Chrome instead
    # This container setup is more for production use

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/example
      - NEO4J_apoc_export_file_enabled=true
      - NEO4j_apoc_import_file_enabled=true
      - NEO4j_apoc_import_file_use__neo4j__config=true

volumes:
  mongodb_data:
  neo4j_data:
  neo4j_logs: